export const layersData = [
  {
    id: "1",
    substance: "Thermal Insulation",
    maker: "T'I",
    product: "200",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 0.07,
    mass: 200,
  },
  {
    id: "2",
    substance: "Thermal Insulation",
    maker: "T'I",
    product: "300",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 0.094,
    mass: 300,
  },
  {
    id: "3",
    substance: "Thermal Insulation",
    maker: "T'I",
    product: "400",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 0.115,
    mass: 400,
  },
  {
    id: "4",
    substance: "Thermal Insulation",
    maker: "Tambur",
    product: "200",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 0.0653,
    mass: 200,
  },
  {
    id: "5",
    substance: "Thermal Insulation",
    maker: "Tambur",
    product: "86",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 0.124,
    mass: 400,
  },
  {
    id: "6",
    substance: "Thermal Insulation",
    maker: "Thermofix",
    product: "750",
    minThickness: 1,
    maxThickness: 5,
    thickness: 1,
    thermalConductivity: 0.086,
    mass: 300,
  },
  {
    id: "7",
    substance: "Thermal Insulation",
    maker: "Thermofix",
    product: "760",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 0.105,
    mass: 400,
  },
  {
    id: "8",
    substance: "Concrete",
    maker: "Regular Concrete",
    product: "Regular Concrete",
    minThickness: 5,
    maxThickness: 100,
    thickness: 5,
    thermalConductivity: 2.1,
    mass: 2400,
  },
  {
    id: "9",
    substance: "Betkal",
    maker: "Light Concrete",
    product: "Light Concrete 1200",
    minThickness: 5,
    maxThickness: 40,
    thickness: 5,
    thermalConductivity: 0.62,
    mass: 1200,
  },
  {
    id: "10",
    substance: "Tit",
    maker: "Tit",
    product: "Melet Chemanty",
    minThickness: 1,
    maxThickness: 8,
    thickness: 1,
    thermalConductivity: 1,
    mass: 1800,
  },
  {
    id: "11",
    substance: "Block",
    maker: "Thermodan",
    product: "Pomis dor 5 - 22",
    minThickness: 220,
    maxThickness: 220,
    thickness: 220,
    thermalConductivity: 0.22,
    mass: 1047,
  },
  {
    id: "12",
    substance: "Block",
    maker: "Thermodan",
    product: "Pomis dor 5 - 30",
    minThickness: 30,
    maxThickness: 30,
    thickness: 30,
    thermalConductivity: 0.3,
    mass: 772,
  },
  {
    id: "13",
    substance: "Block",
    maker: "Thermodan",
    product: "Pomis dor 5 - 25",
    minThickness: 250,
    maxThickness: 250,
    thickness: 250,
    thermalConductivity: 0.227,
    mass: 920,
  },
  {
    id: "14",
    substance: "Block",
    maker: "Itung",
    product: "Block Itung",
    minThickness: 20,
    maxThickness: 30,
    thickness: 20,
    thermalConductivity: 0.1035,
    mass: 400,
  },
  {
    id: "15",
    substance: "Block",
    maker: "Block Ravid",
    product: "Pomis gold 22",
    minThickness: 22,
    maxThickness: 22,
    thickness: 22,
    thermalConductivity: 0.191,
    mass: 801,
  },
  {
    id: "16",
    substance: "Block",
    maker: "Block Ravid",
    product: "Pomis gold 25",
    minThickness: 250,
    maxThickness: 250,
    thickness: 250,
    thermalConductivity: 0.166,
    mass: 867,
  },
  {
    id: "17",
    substance: "Isolation Board",
    maker: "Polybid",
    product: "Board Polish 200",
    minThickness: 2,
    maxThickness: 6,
    thickness: 2,
    thermalConductivity: 0.0676,
    mass: 200,
  },
  {
    id: "18",
    substance: "Isolation Board",
    maker: "Polybid",
    product: "Board Polish Extra",
    minThickness: 2,
    maxThickness: 6,
    thickness: 2,
    thermalConductivity: 0.0513,
    mass: 140,
  },
  {
    id: "19",
    substance: "Isolation Board",
    maker: "Polybid",
    product: "Board Polish Premium",
    minThickness: 2,
    maxThickness: 6,
    thickness: 2,
    thermalConductivity: 0.0456,
    mass: 100,
  },
  {
    id: "20",
    substance: "Isolation Board",
    maker: "Melagol",
    product: "Pomglass",
    minThickness: 3,
    maxThickness: 10,
    thickness: 3,
    thermalConductivity: 0.043,
    mass: 130,
  },
  {
    id: "21",
    substance: "Isolation Board",
    maker: "Melagol",
    product: "Solarglass",
    minThickness: 3,
    maxThickness: 10,
    thickness: 3,
    thermalConductivity: 0.043,
    mass: 120,
  },
  {
    id: "22",
    substance: "Isolation Board",
    maker: "Kal Product Isolation",
    product: "Firetop",
    minThickness: 3,
    maxThickness: 7,
    thickness: 3,
    thermalConductivity: 0.0606,
    mass: 180,
  },
  {
    id: "23",
    substance: "Internal Insulation",
    maker: "Misterfix",
    product: "Fiximo 640",
    minThickness: 1,
    maxThickness: 5,
    thickness: 1,
    thermalConductivity: 0.87,
    mass: 300,
  },
  {
    id: "24",
    substance: "Rock",
    maker: "Granite",
    product: "Granite",
    minThickness: 1,
    maxThickness: 5,
    thickness: 1,
    thermalConductivity: 2.8,
    mass: 2700,
  },
  {
    id: "25",
    substance: "Rock",
    maker: "Marble",
    product: "Marble",
    minThickness: 1,
    maxThickness: 5,
    thickness: 1,
    thermalConductivity: 3.5,
    mass: 2800,
  },
  {
    id: "26",
    substance: "Rock",
    maker: "Gear Rock",
    product: "Gear Rock",
    minThickness: 1,
    maxThickness: 5,
    thickness: 1,
    thermalConductivity: 2.3,
    mass: 2600,
  },
];
